const possibleColors = {
    Placeholder_color1: "placeholder-black/70",
    Placeholder_color2: "placeholder-white/70",
    Hover_Placeholder_color1: "hover:placeholder-teal-800",
    Hover_Placeholder_color2: "hover:placeholder-yellow-400",
    Text_color1: "text-teal-800",
    Text_color2: "text-yellow-400",
    Bg_Alternate_color1: "bg-gray-800",
    Bg_Alternate_color2: "bg-cyan-500",
    Bg_color1: "bg-teal-800",
    Bg_color2: "bg-yellow-400",
    Border_color1: "border-teal-800",
    Border_color2: "border-yellow-400",
    Hover_Alternate_color1: "hover:text-gray-800",
    Hover_Alternate_color2: "hover:text-cyan-500",
    Hover_color1: "hover:text-teal-800",
    Hover_color2: "hover:text-yellow-400",
    Hover_Border_Alternate_color1: "hover:border-gray-800",
    Hover_Border_Alternate_color2: "hover:border-cyan-500",
    Hover_Border_color1: "hover:border-teal-800",
    Hover_Border_color2: "hover:border-yellow-400",
    Shadow_color1: "shadow-teal-400/40",
    Shadow_color2: "shadow-yellow-400/40",
    Faded_text1: "text-black/70",
    Faded_text2: "text-white/70",
};

export default possibleColors;
